# Site settings
title: Pieter Benjamin
email: pieter0benjamin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About Me!
baseurl: "/personal-website" # the subpath of your site, e.g. /blog/
url: "http://pieterBenjamin.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: PieterBenjamin

# Build settings
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
